language: node_js
node_js:
    - "8.12.0"

before_script:
    - npm install -g grunt-cli
    - npm install --quiet
    - npm install -g mocha
    - npm install -g istanbul

#services:
#    - mongodb

script:
    - grunt
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive --timeout 10000 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
